### ISSUE TITLE
Tables contributor week 2024 brainstorming ideas

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/tables#1384]
1. [ ] ✔️✔️✔️✔️✔️✔️✔️ Deep linking: link with built in reference to a row, view, cell. smart picker https://github.com/nextcloud/tables/issues/172
2. [ ] ✔️✔️✔️✔️ Collaborative editing
3. [ ] ✔️✔️✔️ Hide other people's views (a bit of https://github.com/nextcloud/tables/issues/601)
4. [ ] ✔️✔️✔️ Connect forms and tables
5. [ ] ✔️✔️✔️ Desktop client, mobile app or offline mode
6. [ ] ✔️✔️ Filtering a column is not very intuitive/discoverable
7. [ ] ✔️✔️ Move columns https://github.com/nextcloud/tables/issues/607
8. [ ] ✔️✔️Better browsing/navigation of views when there are many of them
9. [ ] ✔️✔️Enable comments for each cell 
10. [ ] ✔️✔️ Pin columns (sticky) https://github.com/nextcloud/tables/issues/613
11. [ ] ✔️Columns description 
12. [ ] ✔️Sharing with teams instead of only with groups https://github.com/nextcloud/tables/issues/142
13. [ ] ✔️Open tables in viewer from other apps
14. [ ] Inline editing (don't vote this one because it's already planned) https://github.com/nextcloud/tables/issues/1389 https://github.com/nextcloud/tables/issues/1268 https://github.com/nextcloud/tables/issues/1313
15. [ ] Performance with big tables may not be great (thousands and tens of thousands of rows)  https://github.com/nextcloud/tables/issues/941 https://github.com/nextcloud/tables/issues/448 
16. [ ] Better way to browse tables and views in the navigation
17. [ ] App-wide search

FYI @juliushaertl @jancborchardt @nimishavijay
