### ISSUE TITLE
Applications: Implement route to show a context

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/tables#864]
Next steps:
- [x] merge #843 
- [x] Talk to @blizzz to rebase #861 on top of latest feat/contexts
- [x] Rebase https://github.com/nextcloud/tables/pull/844 on top of latest enh/noid/contexts-api (#861)
- [x] Continue implementing in #844 
  - [x] Extend the vue route for /context to have an id parameter `/context/{id}`
  - [x] Use backend API to fetch the nodes for the provided context id and show its tables/views

**Comment by blizzz** [comment]
Currently, by #844, the route is the page index with an anchor for the application and its id.

For the navigation in #904, I create the link accordingly via https://github.com/nextcloud/tables/blob/84622c694992bd0c959984f5fcefac47dfb7adc9/lib/Listener/BeforeTemplateRenderedListener.php#L76-L77
