### ISSUE TITLE
Column Types

### ISSUE THREAD

**Issue by enjeck** [nextcloud/tables#981]
This issue tracks Tables column types, both already implemented and user suggestions that we might consider building in the future. 

### Already implemented
- Text
- Rich Text
- Number
- Date (Could allow constant default value: https://github.com/nextcloud/tables/issues/732)
- Time
- Stars
- Single and multi select
- Progress
- Yes/No checkbox
- Links (depends on system setup and Search Provider API):  Files, URL, Notes, Tags, Circles, Comments, Tables, Apps, Settings.
     - User/Contacts (Related issues suggesting enhancements: https://github.com/nextcloud/tables/issues/586, https://github.com/nextcloud/tables/issues/644),

### Suggestions
Some of these were gathered from [Discussions](https://github.com/nextcloud/tables/discussions/20). 
- [ ] Coordinates/Location field with latitude and longitude. Useful for maps integration. Related issue: https://github.com/nextcloud/tables/issues/403
- [ ] Relational field to connect different tables. Related issues: https://github.com/nextcloud/tables/issues/172, https://github.com/nextcloud/tables/issues/802
- [ ] Icon/Emoji picker
- [ ] Color picker
- [ ] Autoincrement / Sequential number
- [ ] Image with preview. Related issue: https://github.com/nextcloud/tables/issues/580. We already have the Link column, and i'd be nice if linked images had a preview. 
- [ ] Drop-down with dependent options e.g country and statefields (you select a country and the state drop-down is limited to the particular country)
- [ ] Formula field. Related issues: https://github.com/nextcloud/tables/issues/181, https://github.com/nextcloud/tables/issues/36, https://github.com/nextcloud/tables/issues/888
- [ ] Email
- [ ] Phone number
- [ ] IP Address. Related issue: https://github.com/nextcloud/tables/issues/402

We should also think about test coverage for the different column types: https://github.com/nextcloud/tables/issues/907

**Comment by enjeck** [comment]
@juliushaertl Coordinates/Location field and  image previews are the most-requested by users for now.

**Comment by juliushaertl** [comment]
Thanks for the nice overview. I think https://github.com/nextcloud/tables/issues/586 is the most crucial one to implement internal processes that we have, which is what we have put on the feature planning board already. 

The file/image one definitely also seems important, we should probably try to figure out how those would be implemented and discuss that further already (e.g. where is the file stored)

**Comment by SystemKeeper** [comment]
Maybe adding a regex validation to the text column would already allow something like an email column? Could even provide some examples to choose from.

**Comment by xbluemonkx** [comment]
I would like to request another (non-editable) column type: user. Because I would like to store the information who created the data set. If you think that through you will end up with
- created by
- created date
- last edited by
- last edited date

**Comment by EzequielBruni** [comment]
Just want to add my voice to the support for Formula fields. Give me that, and I could ditch Airtable, or even my beloved NocoDB. I do like having as much as possible in one place, and all that.

**Comment by Aveyron-RetD** [comment]
What would be interesting for Nextcloud users is having access to Files in a defined folder for some kind of workflow mechanism.
For example : I want to track all the changes inside a folder that are business critical.
I want to notify specific users or groups or all users of a modified document.
I want to know who has opened it and “read it”.
I want to make sure they have read it by making them sign it.  => Maybe by tags ?
I want to know who has not signed it => and send them a reminder.
I want to know who has access to this file in read/Read write/ or no access at all.

It would be much easier to deal with this in a table than going per file and doing all this logic.

**Comment by tatrapikao** [comment]
Id like to suggest a "Label" Value which is similar to the "multi-select" but each string has a configurable Color attached. In the Table it is rendered like this: 
![grafik](https://github.com/user-attachments/assets/7157866e-1401-4b9f-85fe-18fb5bcf8ae4)
preferably there would be the Option to allow the User to add new "Labels" on input or limit them to specific Set.

**Comment by enjeck** [comment]
> Maybe adding a regex validation to the text column would already allow something like an email column? Could even provide some examples to choose from.

for supporting regex, we could do the following because [`[textAllowedPattern](https://github.com/nextcloud/tables/blob/main/lib/Db/Column.php)`](https://github.com/nextcloud/tables/blob/main/lib/Db/Column.php) is already stored and passed through the API.:

**1. Add the validation on the backend.** In [`[TextLineBusiness.php](https://github.com/nextcloud/tables/blob/main/lib/Service/ColumnTypes/TextLineBusiness.php)`](https://github.com/nextcloud/tables/blob/main/lib/Service/ColumnTypes/TextLineBusiness.php), inside `validateValue()`, read `$column->getTextAllowedPattern()`. If it is set and the value is not empty, run `preg_match` and throw a `BadRequestError` when it does not match. This method already runs on every row write, so that one block makes the whole feature work.

**2. Add the input on the frontend.** In [`[TextLineForm.vue](https://github.com/nextcloud/tables/blob/main/src/shared/components/ncTable/partials/columnTypePartials/forms/TextLineForm.vue)`](https://github.com/nextcloud/tables/blob/main/src/shared/components/ncTable/partials/columnTypePartials/forms/TextLineForm.vue), add a text input bound to `textAllowedPattern` so users can set a pattern when creating or editing a text column. Optionally offer a small preset dropdown (e.g IPv4, IPv6, Email) that fills in a vetted pattern, so people do not have to write regex by hand.

**3. Optionally validate while typing.** In [`[textLine.js](https://github.com/nextcloud/tables/blob/main/src/shared/components/ncTable/mixins/columnsTypes/textLine.js)`](https://github.com/nextcloud/tables/blob/main/src/shared/components/ncTable/mixins/columnsTypes/textLine.js) you can check the pattern as the user types and show inline feedback, but the backend check in step 1 is what actually enforces it.

For security:
- First, guard against bad or dangerous regex. Either validate the pattern when the column is saved, or lower the PCRE backtrack limit and treat a failed match as invalid, so a user cannot hang a request with catastrophic backtracking. The preset dropdown sidesteps this entirely. Also, note that the `text-link` subtype reuses the same field for its provider list, so our regex logic stays inside `TextLineBusiness` and does not touch link columns.

**Comment by Aveyron-RetD** [comment]
Realized that i could create a signature column type by using the sketch picker app.
https://apps.nextcloud.com/apps/sketch_picker 
and using a richtextfield column prefilled with /draw when i click on it the selection draw a sketch appears. It's a bad workaround but might work.
It would just need that the richtextfield column as a kind of action on open i do need to click on draw for the sketchpicker to appear while i would like to force the column to a signature type.

<img width="1553" height="314" alt="Image" src="https://github.com/user-attachments/assets/51e251af-0c9c-4228-b561-9534962d00c2" />

Note sketch picker also allows selecting and displaying images

<img width="1551" height="231" alt="Image" src="https://github.com/user-attachments/assets/3d9bd06a-f26d-4b1d-a9f5-036332d7691e" />
