### ISSUE TITLE
Tables versioning and backing up

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/tables#984]
### Is your feature request related to a problem? Please describe.

The app doesn't maintain the trash bin, the export to CSV is not working under some conditions. This may lead to the potential corruption of the data without any possibility to restore it.

### Describe the solution you'd like

Please, add the possibility to have automatic and manual versions of tables, when a user can restore the table on a specific date. Additionally, let a user click on a button to save certain version (including the current one) in the form of CSV table.

**Comment by blizzz** [comment]
I would not see the backup aspect here (export should work, but if there are other errors, we should track and fix them). And after all, there should be the database backup 🙂 

Nevetheless, the versioning aspect is definitely valid.

**Comment by blizzz** [comment]
We figured out that tables would benefit from versioning, to be able to see who changed what and when. With the options to restore. For rows can also be deleted, some sort of trash would be necessary just as well. While in other places versioning and trashbin are separate features, I would like to propose to put it under the **auditing** umbrella.

Further, I propose to make it an opt-in table-specific feature, as on many small instances this is not necessary and only handy on specific tables, that are actually used collaboratively. So we can save some overhead there to make it opt-in only.

Hence it can be enabled by table managers only. 

By permissions, these actions will be possible:
- CREATE: nothing
- READ: show history/versions
- UPDATE: show history/versions, restoration of cell values and of deleted rows
- DELETE: nothing

The feature will be available against views as well, but limited to the visible columns. If a piece of information does not contain changes to any visible row, it will not be shown.

Deleted rows and historic information will expire. The expiration time has be to be an individual setting, as depending on the use case temporal or legal requirements apply. I suggest a default time of **eight weeks**, to avoid ever growing databases. A background job, running in the maintenance window, will finally delete all rows behind that threshold. The configuration will be added to the table.

## Tasks

* [ ] Discuss and agree upon this feature
* [ ] User interface drafts
	* [ ] Create table dialogue
		* Controls to toggle the feature + expiration time
	* [ ] Edit table dialogue
		* Controls to toggle the feature + expiration time
	* [ ] Audit dialogue/modal
		* This is new. How to present changed cells and rows, and deleted rows?
		* Plus conditional controls to restore a version of a cell, or row (both changed and deleted rows)
	* [ ] Table/View page
		* a button to show historic data for the hovered row. Probably a less prominent button next to the **edit** button will do?
		* a way to display deleted rows
* [ ] API drafts
	* [ ] Retrieve historic data for a table and view
		* Consider pagination
	* [ ] Restore a specific cell value, or entire row (also deleted)
	* [ ] Update table properties
		* enable/disable auditing; set expiration time
		* maintain backwards compatibility, default is off
* [ ] DB drafts
	* [ ] reflect *deleted_at* and *deleted_by* states
		* a good candidate would be extending the *oc_tables_row_sleeves* table, but it may contain a lot of data and adding even option columns is (was?) expensive with MySQL/MariaDB.
		* Hence a new, joinable table (maybe *oc_tables_row_trashbin* ?) with this data might be reasonable.
	* [ ] reflect that on update, the previous values should be stored somewhere
		* for each type we have a table of their own and not always with a uniform structure
		* First thoughts:
			* a structural change would be nice (we could append instead of overwrite), but again, is expensive against potentially large tables
			* we could have an `oc_tables_row_cells_history` table that contains all the default information, but also the column type, the column id, but any `value(_a-z*)` column as json inside a `data` or `values` column. 
			* Challenges: 
				- selection-type columns can have their selection changed and assignments might not fit anymore. We have the problem currently, actually (cf. #727), and might be out of scope. It raises the questions though on how to handle structural changes to table columns.
* [ ] Implementations
	* [ ] database schema changes
	* [ ] backend database mappers and entities
	* [ ] backend api and services; integration tests
	* [ ] frontend create/edit dialogue updates; e2e tests
	* [ ] frontend table/view component updates; e2e tests
	* [ ] frontend historic component/dialogue; e2e tests

## Summary

- The **auditing feature** combines versioning, a trashbin and a history of row changes (on cell level were needed)
- It will be **opt-in per table** by table managers. It will be controlled by a check box in the **Create table** and **Edit table** dialogues. Additionally the expiration time can be set there, it defaults to **eight weeks**.
- Users with **READ** permissions will be able to see history and version
- Users with **UPDATE** permission will also be able to see deleted rows and to restore cell values, complete row values, and deleted rows.
- All functions are available with views, but reduced to visible columns. Changes that do not affect any visible row are hidden.
- A background job, that runs in the maintenance window, ensures that expired data will be deleted.

## Questions

- Any opinion on any detail?
- Default expiration time: the thought is that two months are sufficient to address any recent changes. Since it can be overridden it is not a big issue, nevertheless a good default is a good practice. Any thoughts about this?
- Permissions: maybe it is not clear the *READ* and *UPDATE* permissions allow interacting with this auditing feature. Do you think there should be more fine grained control? For instance, restrict to *MANAGE* permissions in general? Perhaps with another opt-in to allow users with *READ+UPDATE* permissions to use it as in the original suggestion? Generally we should avoid too many settings though.
- Should we include the options to purge a specific historic data entry for people with MANAGE permissions? I would refrain from it, there might be the use case to do so when sensitive data was leaked. This goes against the auditing principle though.
- How should we treat structural changes to the table (especially columns changed or removed)?

**Comment by renarios** [comment]
This would be a nice feature!
